### ISSUE TITLE
Can't find the UltimateScoreboards plugin

### ISSUE THREAD

**Issue by CollidaCube** [frengor/UltimateScoreboardsAPI#1]
I went to spigotmc and looked for UltimateScoreboards and I can't find it. I also went to your spigot page and I still can't find the resource.
How tf do you expect me to use this >:[

**Comment by frengor** [comment]
I'm sure you won't find it, it isn't out yet 🙃
And since it isn't published, you're not supposed to use it. 

I tried to publish it one time, but it got refused since UltimateScoreboards would be a premium resource and was considered "low effort". I thought of improving it, but eventually I haven't done it yet.

**Comment by CollidaCube** [comment]
Bruh -_-
